version: '3.9'
services:
  backend:
    build: ./backend
    container_name: fitness-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=fitness_user
      - DB_PASSWORD=fitness_password
      - DB_NAME=fitness_postgres
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    container_name: fitness-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fitness_user
      - POSTGRES_PASSWORD=fitness_password
      - POSTGRES_DB=fitness_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: